### PR TITLE
Add Support For Alignment Specifier In C Struct Declarations

### PR DESCRIPTION
**Pull request by noahmartinwilliams**
C Data structures can now be parsed that have the _Alignas and alignas keywords used in it.

### CODE REVIEW

**Comment by expipiplus1** [comment]
Thank you,

If you add a test and give the version number a minor bump then we can make a release on Hackage.

The last I remember was the the tests were a little tricky, sorry.

**Comment by noahmartinwilliams** [comment]
I can't seem to figure out where the test would fit. test/harness/README says that suite is meant for "existing libraries" (which I'm guessing means compiling C libraries from other projects) and harness is for "tests documenting bugs and problems", but I can't seem to find where I would test new features. Should I just put one in harness?

I'm kind of new to Haskell and it's testing system tbh.

**Comment by expipiplus1** [comment]
Ok, welcome, and no worries, I'll take care of the tests.

I think that this isn't quite correct however. For example it will fail when the alignment specifier is not the first specifier of the first struct member.

I would expect that the example here parses, for example: https://en.cppreference.com/w/c/language/_Alignas

```C
#include <stdalign.h>
#include <stdio.h>
 
// every object of type struct sse_t will be aligned to 16-byte boundary
// (note: needs support for DR 444)
struct sse_t
{
    alignas(16) float sse_data[4];
};
 
// every object of type struct data will be aligned to 128-byte boundary
struct data
{
    char x;
    alignas(128) char cacheline[128]; // over-aligned array of char,
                                      // not array of over-aligned chars
};
 
int main(void)
{
    [printf](http://en.cppreference.com/w/c/io/fprintf)("sizeof(data) = %zu (1 byte + 127 bytes padding + 128-byte array)\n",
           sizeof(struct data));
 
    [printf](http://en.cppreference.com/w/c/io/fprintf)("alignment of sse_t is %zu\n", alignof(struct sse_t));
 
    alignas(2048) struct data d; // this instance of data is aligned even stricter
    (void)d; // suppresses "maybe unused" warning
}
```

**Comment by noahmartinwilliams** [comment]
Does this library support statements that declare a variable? I can't seem to find anything that would allow it to declare a local variable.

**Comment by tomsmeding** [comment]
Hi! Dropping in from outside -- having in `language-c` would be awesome for [Accelerate](https://www.acceleratehs.org/). With this PR, and with an appropriate version bump in `c2hs`, `c2hs` can parse `cuda.h` from Cuda 12. With Noah's other PR to `cuda` this means that Accelerate can support Cuda 12, which would be great. :)

**Comment by Bodigrim** [comment]
@noahmartinwilliams could you possibly rebase?

**Comment by noahmartinwilliams** [comment]
@Bodigrim , ok, rebased.

**Comment by Bodigrim** [comment]
@noahmartinwilliams GitHub UI shows me lots of new files, could you please take another look? Were they added by accident?

**Comment by noahmartinwilliams** [comment]
@Bodigrim . Huh, that's weird. I could have sworn I only changed a few files. I honestly don't know what to do here. I guess they must have somehow been added by accident. I think I saw some of them that looked like they were from my home directory, so maybe there's a bug in git or github?

**Comment by Bodigrim** [comment]
No worries, I rebased myself. Thanks!

**Comment by Bodigrim** [comment]
@tomsmeding @leftaroundabout before I cut a release of `language-c`, could someone please verify that the current `master` branch (commit a81109622aeb15abfe40fb219b8d211415f6ba2a) is capable of parsing `cuda.h`?

**Comment by tomsmeding** [comment]
@Bodigrim Works! Checked a project that indeed fails with language-c from hackage but works with 0.10.0 from master here.

**Pull request merged**
