### PR TITLE
Selectively hide Prelude.<>:  GHC 8.4 compat

### PR DESCRIPTION
**Pull request by deepfire**
Tested on GHC 8.4.1-alpha-1 and 8.0.2.

### CODE REVIEW

**Comment by deepfire** [comment]
@visq, CI failures appear unrelated -- the logs are weirdly empty..

**Comment by lambdageek** [comment]
Wouldn't it be better to hide `(<>)` from `Text.PrettyPrint.HughesPJ` since the Prelude `(<>)` is the future?  Or would that make compatibility with older GHCs more difficult?

**Comment by deepfire** [comment]
Good question -- I haven't explored that.  My intention was to to add as little potential breakage as possible, and hence going for the conservative option, preserving semantics.

The package authors might well prefer to opt for the more forward-looking approach that you suggest.

**Comment by deepfire** [comment]
cc @visq

**Comment by visq** [comment]
Thanks a lot for testing with 8.4 alpha, and providing the fix.
As soon as https://github.com/haskell/pretty makes Doc an instance of Semigroup, we might consider importing Prelude's <> instead; for now, hiding Prelude <> is fine.

**Pull request merged**
